codecov:  
  coverage:
    precision: 2
    round: down
    range: "70...100"
  
    status:
      project:
        default:
          target: 0%
          threshold: 5%
          base: parent
          branches: null
          if_no_uploads: error
          if_not_found: success
          if_ci_failed: error
          only_pulls: false
          flags: null
          paths: null
      patch: no
      changes: no